language: python
python:
  - 2.7
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install -r requirements.txt
script: 
  - ./test/scripts/unit_tests.sh
  - ./test/scripts/integration_test_kinesis.sh
